package com.planora.app.ui.viewmodels

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.planora.app.data.database.entities.Transaction
import com.planora.app.data.database.entities.TransactionType
import com.planora.app.data.repository.SavingsGoalRepository
import com.planora.app.data.repository.TransactionRepository
import com.planora.app.utils.DateUtils
import com.planora.app.utils.PrefsManager
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch
import javax.inject.Inject

enum class MoneyPeriod { ALL, DAILY, WEEKLY, MONTHLY }

data class MoneyUiState(
    val transactions: List<Transaction> = emptyList(),
    val totalIncome: Double = 0.0,
    val totalExpense: Double = 0.0,
    val balance: Double = 0.0,
    val period: MoneyPeriod = MoneyPeriod.ALL,
    val categories: List<String> = emptyList(),
    val categorySpending: Map<String, Double> = emptyMap(),
    val currencySymbol: String = "$"
)

@HiltViewModel
class MoneyViewModel @Inject constructor(
    private val repository: TransactionRepository,
    private val savingsGoalRepository: SavingsGoalRepository,
    prefsManager: PrefsManager
) : ViewModel() {

    private val _period = MutableStateFlow(MoneyPeriod.ALL)

    val uiState: StateFlow<MoneyUiState> = combine(
        _period,
        repository.getAllTransactions().distinctUntilChanged(),
        prefsManager.currencySymbol.distinctUntilChanged()
    ) { period, allTrans, currency ->
        val now = System.currentTimeMillis()
        // Filter by period
        val filtered = when (period) {
            MoneyPeriod.ALL     -> allTrans
            MoneyPeriod.DAILY   -> allTrans.filter { it.date in DateUtils.getDayStart(now)..DateUtils.getDayEnd(now) }
            MoneyPeriod.WEEKLY  -> allTrans.filter { it.date >= DateUtils.getWeekStart(now) }
            MoneyPeriod.MONTHLY -> allTrans.filter { it.date >= DateUtils.getMonthStart(now) }
        }
        // Single-pass: partition once, derive income/expense/categories in one iteration
        var income = 0.0
        var expense = 0.0
        val categorySpending = mutableMapOf<String, Double>()
        for (t in filtered) {
            if (t.type == TransactionType.INCOME) {
                income += t.amount
            } else {
                expense += t.amount
                categorySpending[t.category] = (categorySpending[t.category] ?: 0.0) + t.amount
            }
        }

        val categories = allTrans.map { it.category }.filter { it.isNotBlank() }.distinct().sorted()
        MoneyUiState(
            transactions     = filtered,
            totalIncome      = income,
            totalExpense     = expense,
            balance          = income - expense,
            period           = period,
            categories       = categories,
            categorySpending = categorySpending,
            currencySymbol   = currency
        )
    }.stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), MoneyUiState())

    fun setPeriod(period: MoneyPeriod)    { _period.value = period }
    fun addTransaction(t: Transaction)    = viewModelScope.launch { repository.insertTransaction(t) }
    fun updateTransaction(t: Transaction) = viewModelScope.launch { repository.updateTransaction(t) }
    fun deleteTransaction(t: Transaction) = viewModelScope.launch {
        repository.deleteTransaction(t)
        
        // If this transaction was generated by a savings deposit, deduct it backwards
        if (t.linkedSavingsGoalId != null) {
            val goal = savingsGoalRepository.getGoalById(t.linkedSavingsGoalId)
            if (goal != null) {
                val newAmount = (goal.currentAmount - t.amount).coerceAtLeast(0.0)
                savingsGoalRepository.updateCurrentAmount(goal.id, newAmount)
                
                // If dropping below target, remove completion flag
                if (goal.isCompleted && newAmount < goal.targetAmount) {
                    savingsGoalRepository.updateCompleted(goal.id, false)
                }
            }
        }
    }
    suspend fun getTransactionById(id: Long): Transaction? = repository.getTransactionById(id)
}
